sudo: false
language: scala
scala: 2.11.7
jdk:
- oraclejdk8
notifications:
  slack:
    secure: CsOVBXCU76EnZCqJfJ3azyEDkXsluovgDkbbAJQhK+MflRS9RIhX4KLrjzB3EP+jaliEuHTbWYquF/iKIWeF2fUH1F7U56IUQMQcYfhXKsR5SxXQgnxCP42T19X+VRVJQTxdCOshcMaLZSfnOGGDzKc1FiPqnjc2Xx7Lc+kcBU7v7ZGMtxsLjk0/IGmLPAXbBiRVScnZDTncWH3+K4gv+KO6tIBNnTbho8N12Nq4LqjcCm8qjrBCyFbOZ4mQO1+RhJ+XYpbkL4VyBp6sDPW9qmsOfn0oz9jvAmzoqrFCi4qrdO49iNei1zWZoEMk7AsUzPSQtghQMGLB1tDc9bjcp+H0P8F/KkMwgc4DaEmGlJsqaMVqZEb/DLmXLuQasx6Ub+n6oeXwIjGaxG/IVWFbUYKV1xO9QGU3w8lTZf2rqroXfkSs2bAYqRZfp91FvpyNnE11oRay3AZ/4Oh248H1c5dtK8CE94yRdiCHaaga01QJrz5KFhsqkDXkAq8EYPAmusEUfQ+zzbffWzRJAAWV/U+UJoyAwjgGIPrtyjkkktKc2N3lYXB6bwBdXxzQ5UPUdzyI2uthIZMh9z3VmrlyCzSms1nwaZFAOq4NzuyYB6zVh30dpocWCAFCIGcRjevJX3f8Ju0dgreUuXOS3aiuzW6J4tsg0ungIIOXAi7Fo6g=
